# This workflow loosely replicates the logic in .woodpecker.yml
name: Run Lemmy tests
on:
  push:
    branches:
      - lw-0.*
      - lw-test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: "false"

      - name: Prettier
        uses: docker://tmknom/prettier:3.0.0
        with:
          entrypoint: prettier
          # This does not use shell expansion and arguments are separated with spaces.
          # This is rather janky, a better solution would be to pass a shell script as command.
          args: -c . !**/volumes !**/dist !target !**/translations
