# This workflow loosely replicates the logic in .woodpecker.yml
name: Run Lemmy tests
on:
  push:
    branches:
      - lw-0.*
      - lw-test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: "false"

      - name: Prettier
        uses: docker://tmknom/prettier:3.0.0
        with:
          # args is rather janky for this, as it doesn't deal well with quotes
          # and multiple lines, so it's easier to just put more complex
          # commands in a custom script.
          args: ./.github/scripts/prettier.sh

      - name: TOML fmt
        uses: docker://tamasfe/taplo:0.8.1
        with:
          args: format --check

      - name: SQL fmt
        uses: docker://backplane/pgformatter:latest
        with:
          args: ./scripts/sql_format_check.sh

      - name: Cargo fmt
        uses: docker://rustlang/rust:nightly
        env:
          CARGO_HOME: .cargo_home
        with:
          args: ./.github/scripts/cargo-fmt.sh

      - name: Cargo machete
        uses: docker://rustlang/rust:nightly
        with:
          args: ./.github/scripts/cargo-machete.sh

      - name: Ignored files
        uses: docker://alpine:3
        with:
          args: ./.github/scripts/ignored-files.sh
